Resources:
  AppSyncLambdaServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: ${self:custom.appSync.serviceRole}-appsync-lambda
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "${self:custom.appSync.serviceRole}-${self:provider.stage}-${self:service.name}-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "lambda:invokeFunction"
                Resource:
                  - "arn:aws:lambda:${self:custom.appSync.region}:#{AWS::AccountId}:function:${self:service.name}-${self:provider.stage}-graphql"
                  - "arn:aws:lambda:${self:custom.appSync.region}:#{AWS::AccountId}:function:${self:service.name}-${self:provider.stage}-graphql:*"

  AppSyncDynamoDBServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: ${self:custom.appSync.serviceRole}-appsync-dynamodb
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "${self:custom.appSync.serviceRole}-dynamodb"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:Query"
                  - "dynamodb:BatchWriteItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:Scan"
                  - "dynamodb:UpdateItem"
                Resource:
                  - { Fn::GetAtt: [PostsTable, Arn] }
                  - "Fn::Join":
                      - "/"
                      - - { Fn::GetAtt: ["PostsTable", "Arn"] }
                        - "index/*"
  AppSyncSESserviceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: ${self:custom.appSync.serviceRole}-appsync-ses
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "appsync.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "${self:custom.appSync.serviceRole}-ses"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ses:SendEmail"
                  - "ses:SendRawEmail"
                Resource: "arn:aws:ses:${self:custom.ses.region}:#{AWS::AccountId}:identity/noreply@neami.blue"
