Resources:
  DaxIamRole:
    Type: AWS::IAM::Role
    Properties:
    RoleName: ${self:custom.daxIamRole}
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service: – dax.amazonaws.com
          Action:
            - "sts:AssumeRole"
    Policies:
      - PolicyName: "${self:custom.appSync.serviceRole}-Policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action:
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource:
                Ref: PostsTable

  DaxVpc:
    Type: AWS::EC2::VPC
    Properties:
      InstanceTenancy: default
      CidrBlock: 10.0.0.0/16

  daxSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-southeast-2b
      CidrBlock: 10.0.8.0/24
      VpcId:
        Ref: DaxVpc

  daxSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-southeast-2c
      CidrBlock: 10.0.32.0/24
      VpcId:
        Ref: DaxVpc

  DaxCluster:
    Type: AWS::DAX::Cluster
    Properties:
      ClusterName: ${self:custom.daxClusterName}
      NodeType: dax.t2.small
      ReplicationFactor: 1
      IAMRoleARN:
        Ref: DaxIamRole
      Description: "DAX cluster created with Serverless and Cloudformation"
      SubnetGroupName:
        Ref: DaxSubnetGroup

  DaxSubnetGroup:
    Type: AWS::DAX::SubnetGroup
    Properties:
      DBSubnetGroupDescription: "database subnet group"
      SubnetIds:
        - Ref: daxSubnet1
        - Ref: daxSubnet2
  # DaxVpcSecurityGroup:
  #   Type: "AWS::EC2::SecurityGroup"
  #   Properties:
  #     GroupName: DBSecurityGroup
  #     GroupDescription: Allow local access
  #     SecurityGroupIngress:
  #       - CidrIp: 10.0.0.0/16
  #         IpProtocol: tcp
  #         FromPort: 8111
  #         ToPort: 8111
  #     VpcId:
  #       Ref: DaxVpc
