Resource:
  FormDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.formDataTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      StreamSpecification:
        StreamViewType: NEW_IMAGE
